myapp/apps/todolist/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("<int:page_id>/<str:order_key>/", IndexView.as_view(), name="index"),
    path("todoAdd/", TodoAddView.as_view(), name="todoadd"), 
    path("todoDelete/<int:del_id>/", TodoDeleteView.as_view(), name="tododelete"),
    path("todoEdit/<int:edit_id>/", TodoEditView.as_view(), name="todoedit"),
    path("deletedTodo/",DeletedTodoView.as_view(), name="deletedtodo"),
    path("deleteForever/<int:del_id>/",DeleteForeverView.as_view(), name="deleteforever"),
    path("restore/<int:res_id>/",TodoRestoreView.as_view(), name="restore"),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todolist/", include(("todolist.urls","todolist"),namespace="todolist")),
]

myapp/apps/todolist/models.py
from django.db import models
from db.base_model import BaseModel

# Create your models here.
class MyToDoList(BaseModel):
    title = models.CharField(max_length=255, verbose_name="タイトル")
    contents = models.TextField(verbose_name="詳細")
    deadline = models.DateField(verbose_name="締切")
    done = models.BooleanField(default=False, verbose_name="完成")

    def __str__(self):
        # adminで有意義のobj名を表示
        return self.title

    class Meta:
        # db中の表名前を設定：
        db_table = "todolist" 

        # adminでの表名前を設定：
        verbose_name = "Zwg's ToDoLists" 
        verbose_name_plural = verbose_name

myapp/apps/todolist/forms.py
from django import forms

# 任務追加用フォーム
class ToDoAddForm(forms.Form):
    title = forms.CharField(label="Title",max_length=255)
    contents = forms.CharField(label="内容", widget=forms.Textarea, required=False) # forms包中没有TextFeild
    deadline = forms.DateField(label="締切日")


# 任務削除用フォーム（論理削除）
class ToDoDeleteForm(forms.Form):
    title = forms.CharField(label="Title",max_length=255)
    contents = forms.CharField(label="内容", widget=forms.Textarea, required=False) 
    create_time = forms.DateTimeField(label="作成日")
    deadline = forms.DateField(label="締切日")
    done = forms.BooleanField(label="完成", required=False)

class ToDoEditForm(forms.Form):
    title = forms.CharField(label="Title",max_length=255)
    contents = forms.CharField(label="内容", widget=forms.Textarea, required=False) 
    deadline = forms.DateField(label="締切日")
    done = forms.BooleanField(label="完成", required=False)

myapp/apps/todolist/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse
from django.core.paginator import Paginator
from .models import MyToDoList
from .forms import *

# Create your views here.
# todo一覧
class IndexView(View):
    def get(self, request, page_id=1, order_key="-id"):
        # print("========== order_key: " + order_key + "==========")
        todolist = MyToDoList.objects.filter(is_deleted=False).order_by(f"{order_key}")  # 未論理削除のtodo内容のみ表示
        paginator = Paginator(todolist, 5)  # 全てのデータを5行づつページ分
        current_page = paginator.get_page(page_id)  # page_idのページを取得(画面に表示,default=1)
        nn_page_num = int(page_id) + 2  # 2つあとのページ番号
        params = {
            "paginator":paginator,
            'current_page':current_page,
            "nn_page_num":nn_page_num,
            "order_key":order_key,
            }
        return render(request, 'todolist/index.html', params)

# 追加処理ページ
class TodoAddView(View):
    def get(self, request):
        form = ToDoAddForm()
        params={
            "form":form,
        }
        return render(request, 'todolist/todoAdd.html', params)
        
    def post(self, request):
        title = request.POST.get("title")
        contents = request.POST.get("contents")
        deadline = request.POST.get("deadline")
        MyToDoList.objects.create(title=title, contents=contents, deadline=deadline)
        return redirect(reverse('todolist:index'))

# 削除処理ページ
class TodoDeleteView(View):
    # 削除フォームの表示画面
    def get(self, request, del_id):
        # 記入したtodo内容を取り出し
        tdl_obj = MyToDoList.objects.get(id=del_id)
        context = {
            "title":tdl_obj.title,
            "contents":tdl_obj.contents,
            "create_time":tdl_obj.create_time,
            "deadline":tdl_obj.deadline,
            "done":tdl_obj.done,
        }
        # todo内容をフォームに渡す
        form = ToDoDeleteForm(context)
        params = {
            "form":form,
            "del_id": del_id, 
        }
        return render(request, "todolist/todoDelete.html" , params)

    # 業務処理：論理削除
    def post(self, request, del_id):
        tdl_obj = MyToDoList.objects.get(id=del_id)
        tdl_obj.is_deleted = True
        tdl_obj.save()
        return redirect(reverse('todolist:index'))

# 編集ページ
class TodoEditView(View):
    def get(self, request, edit_id):
        tdl_obj = MyToDoList.objects.get(id=edit_id)
        context = {
            "title":tdl_obj.title,
            "contents":tdl_obj.contents,
            "deadline":tdl_obj.deadline,
            "done":tdl_obj.done,
        }
        form = ToDoEditForm(context)
        params = {
            "form":form,
            "edit_id":edit_id,
        }
        return render(request, "todolist/todoEdit.html", params)

    def post(self, request, edit_id):
        tdl_obj = MyToDoList.objects.get(id=edit_id)
        tdl_obj.title = request.POST.get("title")
        tdl_obj.contents = request.POST.get("contents")
        tdl_obj.deadline = request.POST.get("deadline")
        if request.POST.get("done") == "on":
        # if "done" in request.POST:
            tdl_obj.done = True
        else:
            tdl_obj.done = False
        tdl_obj.save()
        return redirect(reverse('todolist:index'))

# 論理削除一覧
class DeletedTodoView(View):
    def get(self, request,page_id = 1):
        deleted_todo = MyToDoList.objects.filter(is_deleted=True).order_by("-id")  # 未論理削除のtodo内容のみ表示
        params = {
            "deleted_todo":deleted_todo,
            }
        return render(request, 'todolist/deletedTodo.html', params)

# 物理削除機能
class DeleteForeverView(View):
    def get(self, request, del_id):
        if del_id == 0:
            MyToDoList.objects.filter(is_deleted = True).delete()
        else:
            MyToDoList.objects.filter(id=del_id).delete()
        return redirect(reverse('todolist:deletedtodo'))

# 論理削除の回復機能
class TodoRestoreView(View):
    def get(self, request, res_id):
        tdl_obj = MyToDoList.objects.get(id=res_id)
        tdl_obj.is_deleted = False
        tdl_obj.save()
        return redirect(reverse('todolist:deletedtodo')) 

myapp/templates/todolist/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% include 'todolist/menu.html' %}
    <link rel="stylesheet" href="{% static 'todolist/style.css'%}">
    <link rel="stylesheet" href="{% static 'todolist/paginator.css'%}">
</head>
<body>
    <div class="contents">
        <header>
            <div class="app-name">
                <h1><a href="{% url 'todolist:index' %}">ToDoList on Django </a></h1>
            </div>
        </header>
        {% block contents %}{% endblock%}
        <footer>
            <div class="test-right">
                <p>Copyright © 2020, Wengeng Zhang. All rights reserved.</p>
            </div>
        </footer>
    </div>
</body>
</html>

myapp/templates/todolist/deletedTodo.html
{% extends "todolist/base.html" %}
{% block title %}DeletedToDo{% endblock %}
{% block contents %}
<article class="index">
    <div class="page-name">
        <h1>Deleted Todo</h1>
        <div class="alldel"><a href="{% url 'todolist:deleteforever' 0 %}">全て削除</a></div>
    </div>
    <div class="todolist">
        <table>
            <tr class="tb-header">
                <th>Title</th>
                <th>記入日</th>
                <th>締切日</th>
                <th>完了</th>
                <th>復元ボタン</th>
                <th>削除ボタン</th>
            </tr>
            {% for tdl in deleted_todo %}
            <tr class="tdl">
                <td class="title"><a href="{% url 'todolist:todoedit' tdl.id%}">{{ tdl.title }}</a></td>
                <td class="create_time">{{ tdl.create_time|date:"n/j" }}</td>
                <td class="deadline">{{ tdl.deadline|date:"n/j" }}</td>
                <td class="done">
                    {% if tdl.done == False %}
                    <label>✖️</label>
                    {% else %}
                    <label>○</label>
                    {% endif %}
                </td>
                <td class="btn"><a href="{% url 'todolist:restore' tdl.id%}">復元</a></td>
                <td class="btn"><a href="{% url 'todolist:deleteforever' tdl.id%}">永久削除</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</article>
{% endblock %}

myapp/templates/todolist/index.html
{% extends "todolist/base.html" %}
{% block title %}ToDoList Top{% endblock %}
{% block contents %}
<article class="index">
    <div class="page-name">
        <h1>ToDOList</h1>
    </div>
    <div class="todolist">
        <table>
            <tr class="tb-header">
                <th>Title</th>
                <th><a href="{% url 'todolist:index' page_id=current_page.number order_key='-create_time' %}" {% if order_key == '-create_time' %}class="active"{% endif %}>記入日</a></th>
                <th><a href="{% url 'todolist:index' page_id=current_page.number order_key='deadline' %}" {% if order_key == 'deadline' %}class="active"{% endif %}>締切日</a></th>
                <th><a href="{% url 'todolist:index' page_id=current_page.number order_key='done' %}" {% if order_key == 'done' %}class="active"{% endif %}>完成</a></th>
                {% comment %} <th>記入日</th>
                <th>締切日</th>
                <th>完了</th> {% endcomment %}
                <th>削除ボタン</th>
            </tr>
            {# {% for tdl in todolist %} #}
            {% for tdl in current_page %}
            <tr class="tdl">
                <td class="title"><a href="{% url 'todolist:todoedit' tdl.id%}">{{ tdl.title }}</a></td>
                <td class="create_time">{{ tdl.create_time|date:"n/j" }}</td>
                <td class="deadline">{{ tdl.deadline|date:"n/j" }}</td>
                <td class="done">
                    {% if tdl.done == False %}
                    <label>✖️</label>
                    {% else %}
                    <label>○</label>
                    {% endif %}
                </td>
                <td class="btn"><a href="{% url 'todolist:tododelete' tdl.id%}">削除</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    
    {# ページネーション #}
    <div class="pagination">
        <ul>
            {% if current_page.has_previous %}
            <li class="prev"><a href="{% url 'todolist:index' %}{{ current_page.previous_page_number }}"><span>«</span></a>
            </li>
            {% endif %}

            {# 7ページ以上の場合#}
            {% if 7 <= paginator.num_pages %}
                {% if current_page.has_previous %}
                    <li><a href="{% url 'todolist:index' page_id=1 order_key=order_key%}"><span>1</span></a></li>
                    {% if current_page.previous_page_number == 2 %}
                        <li><a href="{% url 'todolist:index' page_id=2 order_key=order_key%}"><span>2</span></a></li>
                    {% elif current_page.previous_page_number > 2 %}
                        <li class="three-points"><a href="#"><span>…</span></a></li>
                        <li><a href="{% url 'todolist:index' page_id=current_page.previous_page_number order_key=order_key%}"><span>{{ current_page.previous_page_number }}</span></a>
                    </li>
                    {% endif %}
                {% endif %}

                <li><a href="{% url 'todolist:index' page_id=current_page.number order_key=order_key%}" class="current-page"><span>{{ current_page.number }}</span></a></li>

                {% if current_page.has_next %}
                    <li><a href="{% url 'todolist:index' page_id=current_page.next_page_number order_key=order_key%}"><span>{{ current_page.next_page_number }}</span></a></li>
                    {% if paginator.num_pages == nn_page_num %}
                        <li><a href="{% url 'todolist:index' page_id=nn_page_num order_key=order_key%}"><span>{{ nn_page_num }}</span></a></li>
                    {% elif paginator.num_pages > nn_page_num %}
                        <li class="three-points"><a href="#"><span>…</span></a></li>
                        <li><a href="{% url 'todolist:index' page_id=paginator.num_pages order_key=order_key%}"><span>{{ paginator.num_pages }}</span></a>
                    </li>
                {% endif %}
            {% endif %}

            {# 7ページ未満場合#}
            {% else %}
                {% for i in paginator.page_range %}
                    {% if i == current_page.number %}
                        <li><a href="{% url 'todolist:index' page_id=i order_key=order_key%}" class="current-page"><span>{{ i }}</span></a></li>
                    {% else %}
                        <li><a href="{% url 'todolist:index' page_id=i order_key=order_key%}"><span>{{ i }}</span></a></li>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% if current_page.has_next %}
                <li class="next"><a href="{% url 'todolist:index' page_id=current_page.next_page_number order_key=order_key%}"><span>»</span></a></li>
            {% endif %}
        </ul>
    </div>
</article>
{% endblock contents %}

myapp/templates/todolist/menu.html
<div class="menu">
    <ul>
        <li><a href="{% url 'todolist:index' %}">Top</a></li>
        <li><a href="{% url 'todolist:todoadd' %}">Add</a></li>
        <li><a href="{% url 'todolist:deletedtodo' %}">Deleted</a></li>
    </ul>
</div>

myapp/templates/todolist/todoAdd.html
{% extends 'todolist/base.html' %}
{% block title %}ToDoAdd{% endblock %}
{% block contents %}
<article class="todoadd">
    <div class="page-name">
        <h1>ToDo追加フォーム</h1>
    </div>
    <div class="todoadd-form">
        <form action="{% url 'todolist:todoadd' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="field-row">
                    {{ field.label_tag }}{{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="添加">
        </form>
    </div>
</article>
{% endblock %}

myapp/templates/todolist/todoDelete.html
{% extends 'todolist/base.html' %}
{% block title %}ToDoDelete{% endblock %}
{% block contents %}
<article class="tododel">
    <div class="page-name">
        <h1>ToDo削除フォーム</h1>
    </div>
    <div class="tododel-form">
        <form action="{% url 'todolist:tododelete' del_id%}" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="field_row">
                {{ field.label_tag }}{{ field }}
            </div>
            {% endfor %}
            <p>本当に削除しますか？</p>
            <input type="submit" value="削除">
        </form>
    </div>
</article>
{% endblock %}

myapp/templates/todolist/todoEdit.html
{% extends 'todolist/base.html' %}
{% block title %}{% endblock %}
{% block contents %}
<article class="todoedit">
    <div class="page-name">
        <h1>ToDo編集フォーム</h1>
    </div>
    <div class="todoedit-form">
        <form action="{% url 'todolist:todoedit' edit_id%}" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="feild-row">
                {{ field.label_tag }}{{ field }}
            </div>
            {% endfor %}
            <input type="submit" value="保存">
        </form>
    </div>
</article>
{% endblock contents%}